### ISSUE TITLE
Have template to create clones of this

### ISSUE THREAD

**Issue by sevagh** [larose/mtl-tech#4]
This type of project is cool for any city/country.

It would be cool if you had some Make-like tool (a makefile or Python script or something), like:

```
./generate_project.py --location="Texas"
```

**Comment by larose** [comment]
Yes or maybe something similar to this: https://whoishiring.io

Pull requests are welcome :)

**Comment by sevagh** [comment]
I'll work on a pull request. Basically by being able to make a clone of this repo, you can make any kind of website. Restaurant locator, pollution warning map, etc. Any industry, any region.

**Comment by sevagh** [comment]
It works. Cloned using the script:

Step 1: create world-wonders repository
Step 2: $ ./clone.sh git@github.com:sevagh/world-wonders.git "World Wonders"
Step 3: go to orgs/ and add your desired orgs (in this case my "orgs" are the 7 Wonders of the Ancient World)
Step 4: Visit http://sevagh.github.io/world-wonders/

https://raw.githubusercontent.com/sevagh/mtl-tech/master/clone.sh

**Comment by sevagh** [comment]
#5
